import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

type ChatPageProps = { messages: string[]; value: string; onChange: (value: string) => void; onSend: () => void };

export function ChatPage({ messages, value, onChange, onSend }: ChatPageProps) {
  return <><View style={styles.header}><Text style={styles.kicker}>SUPPORT</Text><Text style={styles.title}>BuddyBot</Text><Text style={styles.intro}>Quick answers for your driver account and deliveries.</Text></View><View style={styles.panel}>{messages.map((message, index) => <View key={`${message}-${index}`} style={[styles.bubble, index % 2 === 1 && styles.userBubble]}><Text style={[styles.text, index % 2 === 1 && styles.userText]}>{message}</Text></View>)}</View><View style={styles.composer}><TextInput value={value} onChangeText={onChange} placeholder="Ask BuddyBot" placeholderTextColor="#8a9c96" style={styles.input} onSubmitEditing={onSend} returnKeyType="send" /><Pressable onPress={onSend} style={styles.send}><Text style={styles.sendText}>Send</Text></Pressable></View></>;
}

const styles = StyleSheet.create({ header: { paddingTop: 12, paddingBottom: 24 }, kicker: { color: '#81928d', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, title: { color: '#183536', fontSize: 30, fontWeight: '800', marginTop: 6 }, intro: { color: '#71857f', fontSize: 13, lineHeight: 20, marginTop: 8 }, panel: { backgroundColor: '#fff', borderRadius: 15, padding: 16, minHeight: 300, justifyContent: 'flex-end', gap: 10 }, bubble: { alignSelf: 'flex-start', backgroundColor: '#eaf4ef', borderRadius: 12, padding: 12, maxWidth: '85%' }, userBubble: { alignSelf: 'flex-end', backgroundColor: '#173d3c' }, text: { color: '#294444', fontSize: 13, lineHeight: 19 }, userText: { color: '#fff' }, composer: { flexDirection: 'row', marginTop: 12, gap: 8 }, input: { flex: 1, backgroundColor: '#fff', borderRadius: 9, paddingHorizontal: 13, paddingVertical: 11, color: '#294444', fontSize: 13 }, send: { backgroundColor: '#329467', borderRadius: 9, justifyContent: 'center', paddingHorizontal: 14 }, sendText: { color: '#fff', fontSize: 12, fontWeight: '800' } });
