import { Pressable, StyleSheet, Text, View } from 'react-native';

type HomePageProps = { online: boolean; onToggleOnline: () => void; onOpenProfile: () => void; onOpenEarnings: () => void; onOpenWithdraw: () => void; onOpenDeliveries: () => void };

export function HomePage({ online, onToggleOnline, onOpenProfile, onOpenEarnings, onOpenWithdraw, onOpenDeliveries }: HomePageProps) {
  return <>
    <View style={styles.header}><View><Text style={styles.kicker}>SATURDAY, AUGUST 22</Text><Text style={styles.greeting}>Good morning, Alex</Text></View><Pressable onPress={onOpenProfile} style={styles.avatar}><Text style={styles.avatarText}>A</Text></Pressable></View>
    <View style={styles.availability}><View><View style={styles.onlineRow}><View style={[styles.dot, !online && styles.offlineDot]} /><Text style={styles.onlineText}>{online ? 'You are online' : 'You are offline'}</Text></View><Text style={styles.hint}>{online ? 'Ready for your next delivery' : 'Go online to receive jobs'}</Text></View><Pressable onPress={onToggleOnline} style={[styles.toggle, online && styles.toggleOn]} accessibilityRole="switch" accessibilityState={{ checked: online }}><View style={[styles.thumb, online && styles.thumbOn]} /></Pressable></View>
    <View style={homeActionStyles.earningsBlock}><Pressable onPress={onOpenEarnings} style={styles.earnings}><View style={styles.earningMain}><Text style={styles.eyebrow}>TODAY'S EARNINGS</Text><Text style={styles.amount}>$86.40</Text><Text style={styles.meta}>5 deliveries  <Text style={styles.positive}>+12%</Text></Text></View><View style={styles.metric}><Text style={styles.metricValue}>4.9</Text><Text style={styles.metricLabel}>Rating</Text></View><View style={styles.metric}><Text style={styles.metricValue}>3h 24m</Text><Text style={styles.metricLabel}>Online</Text></View></Pressable><Pressable onPress={onOpenWithdraw} style={homeActionStyles.withdrawButton}><Text style={homeActionStyles.withdrawButtonText}>Withdraw earnings</Text></Pressable></View>
    <View style={styles.prompt}><Text style={styles.promptTitle}>Your next stop</Text><Text style={styles.promptText}>Continue your active delivery or check the latest available jobs.</Text><Pressable onPress={onOpenDeliveries} style={styles.promptButton}><Text style={styles.promptButtonText}>Open deliveries</Text></Pressable></View>
  </>;
}

const styles = StyleSheet.create({ header: { backgroundColor: '#102a2b', marginHorizontal: -22, marginTop: -22, padding: 22, paddingBottom: 30, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, kicker: { color: '#9bb3ad', fontSize: 11, fontWeight: '700', letterSpacing: 1.3 }, greeting: { color: '#fff', fontSize: 26, fontWeight: '700', marginTop: 7 }, avatar: { backgroundColor: '#e5b95c', width: 43, height: 43, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#102a2b', fontWeight: '800', fontSize: 17 }, availability: { backgroundColor: '#fff', borderRadius: 14, marginTop: -12, padding: 17, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, onlineRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#38a169' }, offlineDot: { backgroundColor: '#a0aaa6' }, onlineText: { color: '#183536', fontSize: 15, fontWeight: '700' }, hint: { color: '#78908b', fontSize: 12, marginTop: 5 }, toggle: { width: 50, height: 29, borderRadius: 16, backgroundColor: '#d4dfda', padding: 3, justifyContent: 'center' }, toggleOn: { backgroundColor: '#329467' }, thumb: { width: 23, height: 23, borderRadius: 12, backgroundColor: '#fff' }, thumbOn: { alignSelf: 'flex-end' }, earnings: { flexDirection: 'row', paddingVertical: 28, gap: 19 }, earningMain: { flex: 1 }, eyebrow: { color: '#81928d', fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, amount: { color: '#173738', fontSize: 34, fontWeight: '800', marginTop: 4 }, meta: { color: '#6d817b', fontSize: 12, marginTop: 3 }, positive: { color: '#228658', fontWeight: '700' }, metric: { borderLeftWidth: 1, borderLeftColor: '#d9e3de', paddingLeft: 17, justifyContent: 'center', minWidth: 65 }, metricValue: { color: '#173738', fontWeight: '800', fontSize: 16 }, metricLabel: { color: '#81928d', fontSize: 11, marginTop: 5 }, prompt: { backgroundColor: '#eaf4ef', borderRadius: 15, padding: 18, marginBottom: 22 }, promptTitle: { color: '#1f5e4a', fontSize: 16, fontWeight: '800' }, promptText: { color: '#6d817b', fontSize: 12, lineHeight: 18, marginTop: 6 }, promptButton: { alignSelf: 'flex-start', backgroundColor: '#173d3c', borderRadius: 9, paddingVertical: 11, paddingHorizontal: 14, marginTop: 14 }, promptButtonText: { color: '#fff', fontSize: 12, fontWeight: '800' } });

const homeActionStyles = StyleSheet.create({ earningsBlock: { marginBottom: 6 }, withdrawButton: { alignSelf: 'flex-start', borderWidth: 1, borderColor: '#329467', borderRadius: 9, paddingVertical: 11, paddingHorizontal: 14, marginBottom: 20 }, withdrawButtonText: { color: '#1e6e4e', fontSize: 12, fontWeight: '800' } });
