import { Pressable, StyleSheet, Text, View } from 'react-native';

type Meeting = { title: string; host: string; time: string; date: string };
type MeetingsPageProps = { meetingDate: string; selectedDay: number; joinedMeetings: string[]; dates: string[]; days: (number | null)[]; meetings: Meeting[]; onSelectDate: (date: string) => void; onSelectDay: (day: number) => void; onToggleJoin: (title: string) => void };

export function MeetingsPage({ meetingDate, selectedDay, joinedMeetings, dates, days, meetings, onSelectDate, onSelectDay, onToggleJoin }: MeetingsPageProps) {
  const visibleMeetings = meetings.filter((meeting) => meeting.date === meetingDate);
  return <><View style={styles.header}><Text style={styles.kicker}>DRIVER COMMUNITY</Text><Text style={styles.title}>Meetings</Text><Text style={styles.intro}>Join online conversations with the BuddyDrop team.</Text></View><View style={styles.calendar}><View style={styles.calendarHeading}><Text style={styles.calendarTitle}>AUGUST 2026</Text><Text style={styles.hint}>Tap a date to view events</Text></View><View style={styles.weekRow}>{['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'].map((day) => <Text key={day} style={styles.weekDay}>{day}</Text>)}</View><View style={styles.grid}>{days.map((day, index) => day === null ? <View key={`empty-${index}`} style={styles.day} /> : <Pressable key={day} onPress={() => onSelectDay(day)} style={[styles.day, selectedDay === day && styles.selectedDay]}><Text style={[styles.dayText, selectedDay === day && styles.selectedDayText]}>{day}</Text>{[22, 23, 25].includes(day) && <View style={styles.eventDot} />}</Pressable>)}</View><View style={styles.quickDates}>{dates.map((date) => <Pressable key={date} onPress={() => onSelectDate(date)} style={[styles.dateChip, meetingDate === date && styles.activeChip]}><Text style={[styles.dateText, meetingDate === date && styles.activeDateText]}>{date}</Text></Pressable>)}</View></View><Text style={styles.sectionTitle}>Available meetings</Text>{visibleMeetings.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No meetings on this date</Text><Text style={styles.emptyText}>Choose a marked date to see available events.</Text></View> : visibleMeetings.map((meeting) => { const joined = joinedMeetings.includes(meeting.title); return <View key={meeting.title} style={styles.meeting}><View style={styles.time}><Text style={styles.hour}>{meeting.time}</Text><Text style={styles.date}>{meeting.date}</Text></View><View style={styles.copy}><Text style={styles.meetingTitle}>{meeting.title}</Text><Text style={styles.host}>Hosted by {meeting.host}</Text><Pressable onPress={() => onToggleJoin(meeting.title)} style={[styles.join, joined && styles.joined]}><Text style={styles.joinText}>{joined ? 'Joined' : 'Join meeting'}</Text></Pressable></View></View>; })}</>;
}

const styles = StyleSheet.create({ header: { paddingTop: 12, paddingBottom: 24 }, kicker: { color: '#81928d', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, title: { color: '#183536', fontSize: 30, fontWeight: '800', marginTop: 6 }, intro: { color: '#71857f', fontSize: 13, lineHeight: 20, marginTop: 8 }, calendar: { backgroundColor: '#173d3c', borderRadius: 15, padding: 18, marginBottom: 26 }, calendarHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, calendarTitle: { color: '#e5b95c', fontSize: 11, fontWeight: '800', letterSpacing: 1.1 }, hint: { color: '#b7d1c5', fontSize: 10 }, weekRow: { flexDirection: 'row', marginTop: 18 }, weekDay: { color: '#b7d1c5', flex: 1, fontSize: 9, fontWeight: '800', textAlign: 'center' }, grid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 }, day: { width: '14.285%', height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 9 }, selectedDay: { backgroundColor: '#e5b95c' }, dayText: { color: '#fff', fontSize: 12, fontWeight: '700' }, selectedDayText: { color: '#173d3c' }, eventDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#e5b95c', marginTop: 3 }, quickDates: { flexDirection: 'row', gap: 8, marginTop: 12 }, dateChip: { borderWidth: 1, borderColor: '#5b7c73', borderRadius: 8, paddingVertical: 9, paddingHorizontal: 11 }, activeChip: { backgroundColor: '#e5b95c', borderColor: '#e5b95c' }, dateText: { color: '#fff', fontSize: 11, fontWeight: '700' }, activeDateText: { color: '#173d3c' }, sectionTitle: { color: '#183536', fontSize: 18, fontWeight: '800', marginBottom: 12 }, meeting: { backgroundColor: '#fff', borderRadius: 14, padding: 16, flexDirection: 'row', marginBottom: 10 }, time: { width: 76, borderRightWidth: 1, borderRightColor: '#e1eae5' }, hour: { color: '#1e6e4e', fontSize: 13, fontWeight: '800' }, date: { color: '#8a9c96', fontSize: 10, marginTop: 5 }, copy: { flex: 1, paddingLeft: 15 }, meetingTitle: { color: '#294444', fontSize: 14, fontWeight: '800' }, host: { color: '#71857f', fontSize: 11, marginTop: 5 }, join: { alignSelf: 'flex-start', backgroundColor: '#173d3c', borderRadius: 8, paddingVertical: 9, paddingHorizontal: 12, marginTop: 13 }, joined: { backgroundColor: '#329467' }, joinText: { color: '#fff', fontSize: 11, fontWeight: '800' }, empty: { backgroundColor: '#eaf4ef', borderRadius: 13, padding: 20 }, emptyTitle: { color: '#1f5e4a', fontSize: 14, fontWeight: '800' }, emptyText: { color: '#6d817b', fontSize: 12, marginTop: 5 } });
