import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';

export type SurgePlace = { name: string; area: string; distance: string; demand: string; bonus: string; query: string };
type SurgePageProps = { places: SurgePlace[] };

export function SurgePage({ places }: SurgePageProps) {
  const openDirections = (query: string) => Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`);

  return <><View style={styles.header}><Text style={styles.kicker}>LIVE DRIVER MAP</Text><Text style={styles.title}>Surge places</Text><Text style={styles.intro}>Move toward high-demand areas to find more delivery requests.</Text></View><View style={styles.notice}><Text style={styles.noticeTitle}>Demand is changing live</Text><Text style={styles.noticeText}>Bonuses can change as drivers arrive and orders are completed.</Text></View><Text style={styles.sectionTitle}>Nearby high-demand areas</Text>{places.map((place) => <View key={place.name} style={styles.card}><View style={styles.cardTop}><View><Text style={styles.placeName}>{place.name}</Text><Text style={styles.area}>{place.area}  ·  {place.distance}</Text></View><Text style={styles.bonus}>{place.bonus}</Text></View><View style={styles.stats}><View><Text style={styles.statLabel}>DEMAND</Text><Text style={styles.statValue}>{place.demand}</Text></View><View><Text style={styles.statLabel}>EST. EXTRA / HR</Text><Text style={styles.statValue}>{place.bonus}</Text></View></View><Pressable onPress={() => openDirections(place.query)} style={styles.directions}><Text style={styles.directionsText}>Open directions</Text><Text style={styles.arrow}>&gt;</Text></Pressable></View>)}</>;
}

const styles = StyleSheet.create({ header: { paddingTop: 12, paddingBottom: 24 }, kicker: { color: '#81928d', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, title: { color: '#183536', fontSize: 30, fontWeight: '800', marginTop: 6 }, intro: { color: '#71857f', fontSize: 13, lineHeight: 20, marginTop: 8 }, notice: { backgroundColor: '#173d3c', borderRadius: 15, padding: 18, marginBottom: 26 }, noticeTitle: { color: '#e5b95c', fontSize: 15, fontWeight: '800' }, noticeText: { color: '#d1e1da', fontSize: 12, lineHeight: 18, marginTop: 6 }, sectionTitle: { color: '#183536', fontSize: 18, fontWeight: '800', marginBottom: 12 }, card: { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 11 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, placeName: { color: '#294444', fontSize: 15, fontWeight: '800' }, area: { color: '#71857f', fontSize: 11, marginTop: 5 }, bonus: { color: '#1e6e4e', fontSize: 16, fontWeight: '800' }, stats: { flexDirection: 'row', gap: 42, borderTopWidth: 1, borderTopColor: '#edf1ef', borderBottomWidth: 1, borderBottomColor: '#edf1ef', paddingVertical: 13, marginTop: 15 }, statLabel: { color: '#8a9c96', fontSize: 9, fontWeight: '800', letterSpacing: 0.7 }, statValue: { color: '#294444', fontSize: 13, fontWeight: '800', marginTop: 4 }, directions: { backgroundColor: '#eaf4ef', borderRadius: 9, paddingVertical: 12, paddingHorizontal: 14, marginTop: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, directionsText: { color: '#1e6e4e', fontSize: 12, fontWeight: '800' }, arrow: { color: '#1e6e4e', fontSize: 18 } });
